# email_list.py

email_list = [
    'ebenmills200@gmail.com',
    kentsiwah@gmail.com,
beechem.micheal20@central.edu.gh
miezah.uzziel.kakuchie20@central.edu.gh
abu.joseph18@central.edu.gh
alornyo.kalvin19@central.edu.gh
baiden.jason19@central.edu.gh
erivona.oghenetega19@central.edu.gh
abolarin.abeeb18@central.edu.gh
james.agbedor16@central.edu.gh
anane.samuel18@central.edu.gh
arnold.awatey@central.edu.gh
kwayisi.barimah@central.edu.gh
jonathan.doku16@central.edu.gh
gyawu.jeremy19@central.edu.gh
lartey.simon18@central.edu.gh
martin.nsoh17@central.edu.gh
richard.ofori.amanfo17@central.edu.gh
owusu.siabuor18@central.edu.gh
nana.aboagye16@central.edu.gh
akoto.richard19@central.edu.gh
cudjoe.benjamin19@central.edu.gh
otoo.richmond19@central.edu.gh
sodacash88@gmail.com
bankboamah@gmail.com
attafuah100@gmail.com
pyamintah2@gmail.com
chakiliakuroboi@gmail.com
moforidebrah1980@gmail.com
erickwame1984@gmail.com
sedemyehowa@gmail.com
danielanyetei@gmail.com
dzawui.joseph@yahoo.com
manueljiant@gmail.com
nanasam951@gmail.com
abdul.rahman.mahama@central.edu.gh
alhasssanduani.amin20@central.edu.gh
annan.prah.leonard.augustine20@central.edu.gh
asare.clement.kofi20@central.edu.gh
ayivor.samuel.makafui20@central.edu.gh
boamah.isaac.duah20@central.edu.gh
felbah.andrea.maame20@central.edu.gh
issah.ibrahim@central.edu.gh
mensah.philip.abam20@central.edu.gh
nortey.frank20@central.edu.gh
odoom.philip20@central.edu.gh
suleman.shuaib20@central.edu.gh
umarmohammed.basiru20@central.edu.gh
amihere.emmanuel.naykene20@central.edu.gh
boafo.abraham20@central.edu.gh
logah.francis.xian20@central.edu.gh
oduro.nyarko.bernard20@central.edu.gh
tsetsro.moses20@central.edu.gh
pious.abakah@central.edu.gh
frederick.acheampong@central.edu.gh
gabriel.amponsahababio@central.edu.gh
jacob.ayuungo@central.edu.gh
cobbinah.prince19@central.edu.gh
dzata.selorm19@central.edu.gh
nuhu.seesi19@central.edu.gh
sarpong.emmanuel19@central.edu.gh
aboki.spencer18@central.edu.gh
addy.george18@central.edu.gh
akumun.solomon19@central.edu.gh
augustine.amissare@central.edu.gh
antwi.isaac19@central.edu.gh
asare.nana19@central.edu.gh
bannah.daniel18@central.edu.gh
donkor.edem19@central.edu.gh
charles.frimpong-asare@central.edu.gh
gyamfi.adu19@central.edu.gh
kpangkpari.gerald18@central.edu.gh
martinson.alex19@central.edu.gh
paul.opoku@central.edu.gh
otoo.gregory19@central.edu.gh
sackey.reuben19@central.edu.gh
totime.robert18@central.edu.gh
afuugu.john19@central.edu.gh
amesimeku.julius19@central.edu.gh
azangweo.shadrach19@central.edu.gh
doe.james19@central.edu.gh
dan.kwawu@central.edu.gh
aliu.mohammed17@central.edu.gh
saeed.abdullai19@central.edu.gh
jeffterjoel@gmail.com
kidisil.moses.yimbilibe20@central.edu.gh
owens.steve.eli20@central.edu.gh
acquaye.albert19@central.edu.gh
amanor.paul19@central.edu.gh
bosrotsi.rhinefried19@central.edu.gh
jones.el19@central.edu.gh
nunoo.john19@central.edu.gh
prah.nash19@central.edu.gh
quaicoe.polycarp19@central.edu.gh
michael.acquaah.harrison17@central.edu.gh
agyemang.nana18@central.edu.gh
augustine.arvoh.mensah17@central.edu.gh
ayaribila.desmond18@central.edu.gh
bayelladong.benedict18@central.edu.gh
dosoo.joseph18@central.edu.gh
harrison.james18@central.edu.gh
mawutor.morttey16@central.edu.gh
numoah.daniel18@central.edu.gh
ofori.alex18@central.edu.gh
prah.kelvin.18@central.edu.gh
edward.addo.yobo17@central.edu.gh
appiah.sylvester19@central.edu.gh
kumah.nathaniel18@central.edu.gh
kudomor.mark18@central.edu.gh
donriddles@gmail.com
afforvic@gmail.com
fatwoode2002@yahoo.com
awusurichard@gmail.com
diawuodennis@yahoo.com
freebonah@gmail.com
tijambaisaac@gmail.com
edwardaidoo647@yahoo.com
donlawson99@gmail.com
markenamevo.gudu@yahoo.com
trophatta@gmail.com
wradieric@gmail.com
quainoo.nana.yaw@central.edu.gh
amoah.isaac.owusu20@central.edu.gh
anno.samuel.kwarteng20@central.edu.gh
atakora.yeboah.yaw20@central.edu.gh
bannerman.edward.patrick20@central.edu.gh
boateng.nana.kwame20@central.edu.gh
forson.prince.dominic20@central.edu.gh
kuug.bernard.bernaabzor20@central.edu.gh
mohammed.alhassan20@central.edu.gh
nortey.nii.norte20@central.edu.gh
offeiasamoah.philip20@central.edu.gh
sunu.wyse.koku20@central.edu.gh
zor.jeremiah.benjamin@central.edu.gh
antwi.gyimah.frank@central.edu.gh
cobbina.samuel.akompong20@central.edu.gh
nifaaniteng.banabas@central.edu.gh
oppong.danquah.amos20@central.edu.gh
wussah.samuel.lawer20@central.edu.gh
abdallah.seidu19@central.edu.gh
adampah.selassie19@central.edu.gh
appiah.dennis19@central.edu.gh
kwadwo.bediako.baryeh@central.edu.gh
codjoe.patrick18@central.edu.gh
isaac.egyir@central.edu.gh
obeng.wisdom19@central.edu.gh
ustarz.hamza19@central.edu.gh
abubakari.nurideen19@central.edu.gh
joshua.adjei.kumi16@central.edu.gh
abu.alhajj.omar17@central.edu.gh
ampaben.kwabena20@central.edu.gh
kingsley.appiah@central.edu.gh
avuletey.dennis19@central.edu.gh
boatenglaw.alex18@central.edu.gh
donkor.patrick19@central.edu.gh
frimpong.kenneth18@central.edu.gh
geoffrey.kagbetor@central.edu.gh
larbie.raymond19@central.edu.gh
nandi.bageensun19@central.edu.gh
opoku.henry18@central.edu.gh
quaicoe.felix19@central.edu.gh
sam.jonathan19@central.edu.gh
tweneboah.alexander18@central.edu.gh
agbodo.emmanuel19@central.edu.gh
amoa.mensah.kwabena.agyei@central.edu.gh
baah.patrick19@central.edu.gh
gaisie.ben19@central.edu.gh
lumor.confidence19@central.edu.gh
nana.michael19@central.edu.gh
tetteh.michael19@central.edu.gh
elnafajo@yahoo.com
adjei.shidaa.ayorkor20@central.edu.gh
amadu.adama19@central.edu.gh
ashong.rachael.naa20@central.edu.gh
boamah.nana.adjoa20@central.edu.gh
abena.fiergbor20@central.edu.gh
gyekye.priscilla.nana20@central.edu.gh
queenly.pappoe20@central.edu.gh
adams.sabbeth19@central.edu.gh
afedzie.francisca19@central.edu.gh
agyemang.priscilla19@central.edu.gh
appiah.jirephine19@central.edu.gh
atsu.regina19@central.edu.gh
benyin.alberta19@central.edu.gh
difonu.emmanuella19@central.edu.gh
francis.latipher19@central.edu.gh
kordah.sandra19@central.edu.gh
mohammed.sekinatu19@central.edu.gh
oladipo.oluwatomisin19@central.edu.gh
pentil.stephanie19@central.edu.gh
tetteh.chrystabel19@central.edu.gh
zumah.naomi19@central.edu.gh
ackah.eunice18@central.edu.gh
amankwah.esther18@central.edu.gh
bernadette.ankuvie17@central.edu.gh
ama.asante17@central.edu.gh
antoinette.asmah17@central.edu.gh
borsor.felicia18@central.edu.gh
deikumah.anthonia18@central.edu.gh
jennifer.frempong17@central.edu.gh
intsiful.elizabeth18@central.edu.gh
winnifred.lartey17@central.edu.gh
evelyn.nartey17@central.edu.gh
nyuori.sylvia18@central.edu.gh
chelsea.osafo17@central.edu.gh
quarshie.sarah18@central.edu.gh
rena.dornukuor.sappor@central.edu.gh
tsiase.josephine19@central.edu.gh
yorke.edwina18@central.edu.gh
adams.huzeifatu19@central.edu.gh
arhin.judith18@central.edu.gh
darku.benita18@central.edu.gh
pepertua83@gmail.com
menscage@yahoo.co.uk
giftykopp@yahoo.com
terakuu12@gmail.com
bodorachel@gmail.com
naadeilah2299@gmail.com
antwi.comfort19@central.edu.gh
alhassan.kyerewaa20@central.edu.gh
ansah.ama.korang20@central.edu.gh
avormey.rejoice.yaa20@central.edu.gh
duoduaa.nancy20@central.edu.gh
makumator.bernice20@central.edu.gh
oppong.anna20@central.edu.gh
yeboah.patricia.nana.akua@central.edu.gh
ashade.hannah20@central.edu.gh
martin.juliet.abiana20@central.edu.gh
abena.antwi16@central.edu.gh
boateng.evelyn19@central.edu.gh
asante.victoria19@central.edu.gh
shirley.anaman@central.edu.gh
asare.natasha20@central.edu.gh
gifty.boateng@central.edu.gh
dadzie.savita18@central.edu.gh
kumah.barbara20@central.edu.gh
obuobi.addobea19@central.edu.gh
otumi.yvonne20@central.edu.gh
mabel.sasah16@central.edu.gh
agbenyega.judith19@central.edu.gh
fleming.pauline19@central.edu.gh
mensah.edna20@central.edu.gh
sarpong.esther19@central.edu.gh
victoria.mirekua@central.edu.gh
adenuga.quareebat.adejumoke20@central.edu.gh
alornyeku.sharon.yayra20@central.edu.gh
arthiabah.nshiraba.akasi20@central.edu.gh
blessed.ononeze.glory.amarachi20@central.edu.gh
dodoo.benedicta20@central.edu.gh
gyekye.priscilla18@central.edu.gh
akua.owusu20@central.edu.gh
tamakloe.happy20@central.edu.gh
abdullah.nadia19@central.edu.gh
addo.nana19@central.edu.gh
agyei.precious19@central.edu.gh
amankwah.akua19@central.edu.gh
asiklu.priscilla19@central.edu.gh
baidoo.kezia@central.edu.gh
danso.dorcas19@central.edu.gh
fiakpornu.derica19@central.edu.gh
kokoroko.eunice19@central.edu.gh
mensah.elsie19@central.edu.gh
ogwoh.miriam19@central.edu.gh
ellen.segbawu@central.edu.gh
yakubu.nadiatu19@central.edu.gh
araba.abedu17@central.edu.gh
alhassan.ansar18@central.edu.gh
andoh.dorothy18@central.edu.gh
benedicta.asamoah.antwi17@central.edu.gh
naa.ashrifie17@central.edu.gh
boakye.mary18@central.edu.gh
dapaah.eunice16@central.edu.gh
fevlo.naomi18@central.edu.gh
ibrahim.patience19@central.edu.gh
kissi.maame16@central.edu.gh
joy.mireku17@central.edu.gh
nwafor.kate19@central.edu.gh
opoku.priscilla18@central.edu.gh
parker.elaine19@central.edu.gh
salifu.alimatu18@central.edu.gh
tetteh.adeline18@central.edu.gh
wendy.yohuno@central.edu.gh
aboagye.anita18@central.edu.gh
antwi.bridget19@central.edu.gh
dankwa.rita19@central.edu.gh
prempeh.yvonne18@central.edu.gh
amary3796@gmail.com
joybkanor71@gmail.com
akosuaj233@gmail.com
ivy.awuranyi@yahoo.com
parkins.jennifer456@gmail.com
venessa.amankwaah@central.edu.gh
abrokwa.amma.adobea@central.edu.gh
ankude.rubby.yawa20@central.edu.gh
asanteampadu.kate.vardon20@central.edu.gh
dodoo.rebecca20@central.edu.gh
kyere.esther.ama20@central.edu.gh
opoku.wilson.gloria20@central.edu.gh
yankah.sharon20@central.edu.gh
adzika.francisca.afflu20@central.edu.gh
biney.benedicta.kailey20@central.edu.gh
senaya.tasha.mimi20@central.edu.gh
amankwah.beatrice19@central.edu.gh
abremkwaw.ellen19@central.edu.gh
ameyaw.linda18@central.edu.gh
asare.grace20@central.edu.gh
boafo.vida19@central.edu.gh
eunice.crentsil@central.edu.gh
fugah.agnes18@central.edu.gh
esther.nargeh@central.edu.gh
otoo.prisca19@central.edu.gh
samlafo.afi19@central.edu.gh
agbemava.cecilia19@central.edu.gh
danquah.agnes19@central.edu.gh
kuwornu.esther19@central.edu.gh
saaka.salima19@central.edu.gh
horrahim731@gmail.com
bernard.atitsogbui@central.edu.gh
meko.kelvin.abiola20@central.edu.gh
wisdom.sokpor20@central.edu.gh
adzei.nii19@central.edu.gh
afriyie.maxwell19@central.edu.gh
asante.francis19@central.edu.gh
diaba.kafui19@central.edu.gh
nartey.theophilus19@central.edu.gh
plange.abdul19@central.edu.gh
sosu.dorothy19@central.edu.gh
felix.adofo.asamoah17@central.edu.gh
amoah.ato18@central.edu.gh
attafuah.kwame18@central.edu.gh
baah.kelly19@central.edu.gh
cheffa.rauf19@central.edu.gh
geoffrey.isaac18@central.edu.gh
krampah.baidoo18@central.edu.gh
narwortey.justice18@central.edu.gh
eugene.ofori17@central.edu.gh
felix.otoo17@central.edu.gh
nana.yirenkyi.boafo17@central.edu.gh
agbedanu.selase19@central.edu.gh
george.williams.coffie@central.edu.gh
emmanuel.obetesebi.lamptey@central.edu.gh
prophetkumin@gmail.com
kwabenaaboagye@gmail.com
ariseansah95@gmail.com
solomonawonyi@gmail.com
boamaheric16@gmail.com
sypkobby@yahoo.com
bsomiah@st.ug.edu.gh
saintrichie2013@gmail.com
amdanny1@gmail.com
caesar.ebenezertetteh@yahoo.com
kumikwame@yahoo.com
courageousgh@gmail.com
sidney.braimah@central.edu.gh
addo.justice.kafui20@central.edu.gh
annan.david.konney20@central.edu.gh
asante.albert.papa20@central.edu.gh
ayitah.martin.agyeman20@central.edu.gh
boadi.godfred.fiifi20@central.edu.gh
donkor.george.kwesi@central.edu.gh
ibrahim.umar.faruk20@central.edu.gh
larbi.eugenia.adubea20@central.edu.gh
ndekugri.fuseini20@central.edu.gh
odoi.isaac.nii20@central.edu.gh
owusu.gyan.joan20@central.edu.gh
torkpettey.silas.doh20@central.edu.gh
amedome.gideon20@central.edu.gh
boachie.samuel.fordjour20@central.edu.gh
william.jabialu@central.edu.gh
obeng.isaac20@central.edu.gh
owusu.stephen.ntori20@central.edu.gh
oppong.nana18@central.edu.gh
ali.mohammed19@central.edu.gh
asare.daniel18@central.edu.gh
brenya.peter19@central.edu.gh
donkor.hayford19@central.edu.gh
mansuru.saalim19@central.edu.gh
owusu.christian19@central.edu.gh
yeboah.peter19@central.edu.gh
addo.james19@central.edu.gh
adu.victor19@central.edu.gh
amewode.sebastian19@central.edu.gh
anthonio.godly19@central.edu.gh
asamoah.akwasi19@central.edu.gh
ayidzoe.divine20@central.edu.gh
dampare.prince19@central.edu.gh
ebisah.edward19@central.edu.gh
gaisie.peter20@central.edu.gh
kotoku.mawuena19@central.edu.gh
macclean.lovelace.dodoo@central.edu.gh
isaiah.oduro17@central.edu.gh
oti.benson19@central.edu.gh
prince.quarshie17@central.edu.gh
sey.francis19@central.edu.gh
jonas.yengnibeh17@central.edu.gh
akoto.prince19@central.edu.gh
attipoe.thywill19@central.edu.gh
kplorm.demanya@central.edu.gh
kpedor.bryan19@central.edu.gh
godwin.menah17@central.edu.gh
edward.owusu.biney17@central.edu.gh
anaawenjaabrebecca@gmail.com
evarestaezekiel@gmail.com
addae.ewurabena.nyantakyi20@central.edu.gh
alajemba.honour.chuks20@central.edu.gh
ampong.maame.esi20@central.edu.gh
atsu.enyonam20@central.edu.gh
buah.natalia.nyamekeh@central.edu.gh
dadzie.martha20@central.edu.gh
gyamprah.jane.lily20@central.edu.gh
nyaletey.bernice.sedinam20@central.edu.gh
sarpong.francisca.adjei20@central.edu.gh
jennifer.tetteh20@central.edu.gh
addo.beverly19@central.edu.gh
agbodzalu.rosemary19@central.edu.gh
akoto.irene19@central.edu.gh
asamoah.animah19@central.edu.gh
aubyn.chelsea19@central.edu.gh
awuah.mabel19@central.edu.gh
boateng.ivy19@central.edu.gh
evelyn.tetteh19@central.edu.gh
hajarah.ibrahim@central.edu.gh
lemm.stefanie20@central.edu.gh
madugu.dorcas19@central.edu.gh
musah.asia18@central.edu.gh
ofori.lydia19@central.edu.gh
owusu.isabella19@central.edu.gh
owusu.shantel20@central.edu.gh
sackey.jennifer19@central.edu.gh
titi.adwoa19@central.edu.gh
aisha.abbdul.wahab17@central.edu.gh
adjoboah.francisca18@central.edu.gh
deborah.ahiadormey17@central.edu.gh
amos.unen19@central.edu.gh
anyorigiya.gloria18@central.edu.gh
renee.ashiboye17@central.edu.gh
bataka.apith19@central.edu.gh
cherney.vanessa19@central.edu.gh
belinda.daniels16@central.edu.gh
eze.onyeka18@central.edu.gh
aku.hammond17@central.edu.gh
nathalie.kaslee.foh16@central.edu.gh
princess.mensah17@central.edu.gh
nkrumah.hannah18@central.edu.gh
nhyira.nsiah17@central.edu.gh
okine.audrey18@central.edu.gh
mirrian.otu@central.edu.gh
alberta.sagoe17@central.edu.gh
takyi.eloise18@central.edu.gh
shirley.yalley@central.edu.gh
ama.yamoah.boakye16@central.edu.gh
mensah.winifred19@central.edu.gh
amega.mavis18@central.edu.gh
boateng.maame19@central.edu.gh
ziyad.musah16@central.edu.gh
phansonamankwah@gmail.com
kwaliceasnte@gmail.com
monquayson@gmail.com
quarshie5@gmail.com
nobela.yiri@yahoo.co.uk
stephadjoa@gmail.com
victoryexcel3@gmail.com
adams.lydia19@central.edu.gh
tawiah.gertrude19@central.edu.gh
andoh.mensah.victoria20@central.edu.gh
asah.bediako.keneritt20@central.edu.gh
dadzie.esther.baaba20@central.edu.gh
hagan.abigail.ago20@central.edu.gh
kwakye.deborah20@central.edu.gh
nartey.felicia20@central.edu.gh
tetteh.ashong.emmanuella20@central.edu.gh
adanuvor.kekeli.emefa20@central.edu.gh
bawa.nasiba.mbabe20@central.edu.gh
ofori.kwakye.abigail20@central.edu.gh
opare.clara.akosua20@central.edu.gh
amadu.atika19@central.edu.gh
osam.karen19@central.edu.gh
akrofi.tracy20@central.edu.gh
sophia.armstrong17@central.edu.gh
attoh.rachael19@central.edu.gh
bawuah.evelyn18@central.edu.gh
charway.amanda18@central.edu.gh
afuah.febri.yeboah17@central.edu.gh
morrison.cynthia.senam@central.edu.gh
ogoe.anthoinette19@central.edu.gh
peasah.vera20@central.edu.gh
adenusi.naomi19@central.edu.gh
budu.theresa19@central.edu.gh
gozey.sena19@central.edu.gh
valerie.okaiteh@central.edu.gh
asemnor.maame.efua20@central.edu.gh
kpodovia.ferdinand.lawson20@central.edu.gh
owusu.linus.nana20@central.edu.gh
amponsah.maxwell19@central.edu.gh
de.richard19@central.edu.gh
mensah.hayford19@central.edu.gh
nortey.ransford20@central.edu.gh
obeng.obrempong20@central.edu.gh
sosu.deladem19@central.edu.gh
adjei.frank18@central.edu.gh
alhassan.buhari19@central.edu.gh
patrick.assem16@central.edu.gh
ayirebi.opoku18@central.edu.gh
marcus.bentil17@central.edu.gh
ekpendu.godfrey18@central.edu.gh
derrick.kpogoh16@central.edu.gh
nambaah.franklin18@central.edu.gh
kelvin.asiedu.obeng@central.edu.gh
osei.noah19@central.edu.gh
roger.yendaw16@central.edu.gh
aganzua.emmanuel19@central.edu.gh
awuku.ernest19@central.edu.gh
erasmus.nayo17@central.edu.gh
konlansimonyennuturin@gmail.com
jmastaj5g5@yahoo.com
sanda.amadu@gmail.com
awedaga10@yahoo.com
kwabena.baffour-kumah@gepa.gov.gh
fuahjed@gmail.com
nanayawbadu31@gmail.com
albertamofaadade@yahoo.com
kwabenajacey@gmail.com
asilevicollins@gmail.com
thomasjumpah@gmail.com
dominic.osei@ymail.com
arthur.alphonse19@central.edu.gh
sarpong.akwasi19@central.edu.gh
anamoah.dennis.abeiku20@central.edu.gh
asamoah.kwame20@central.edu.gh
awudi.charles20@central.edu.gh
basiru.abdul.rahaman20@central.edu.gh
dadzie.ediecarl.ekow20@central.edu.gh
gotah.larry.lumor20@central.edu.gh
lamptey.abraham.krist20@central.edu.gh
mohammedlawal.ma.awiya20@central.edu.gh
odametey.samuel20@central.edu.gh
owusu.francis.junior20@central.edu.gh
tetteh.charles.bernard20@central.edu.gh
alhassan.abdul.ganiyu20@central.edu.gh
gabriel.arthur@central.edu.gh
cobbinah.jonathan.nelson20@central.edu.gh
ntsri.gershon20@central.edu.gh
osah.kartey.dickson20@central.edu.gh
nketiah.kwame18@central.edu.gh
abubakari.mohaisen18@central.edu.gh
adu.andrew19@central.edu.gh
arthur.prince19@central.edu.gh
boakye.manu18@central.edu.gh
darko.kwaku18@central.edu.gh
frans.joachim20@central.edu.gh
ofori.isaac19@central.edu.gh
vugah.wisdom19@central.edu.gh
acheampong.isaac19@central.edu.gh
emmanuel.adjiri@central.edu.gh
amekor.isaac19@central.edu.gh
anorkwah.andrew19@central.edu.gh
archer.gideon19@central.edu.gh
derek.ayamgba@central.edu.gh
brown.adotey18@central.edu.gh
dziwornu.innocent19@central.edu.gh
frimpong.kojo19@central.edu.gh
kekeshie.clifford16@central.edu.gh
lindsay.alexander18@central.edu.gh
nyanor.nathaniel18@central.edu.gh
osei.philip19@central.edu.gh
richard.quainoo@central.edu.gh
seshie.romeo18@central.edu.gh
yakubu.fuseini20@central.edu.gh
akakpo.salifu19@central.edu.gh
ampah.simon19@central.edu.gh
botchway.daniel19@central.edu.gh
korang.christian19@central.edu.gh
isaac.maccarthy16@central.edu.gh
nkrahene.osei19@central.edu.gh
torwoe.benard18@central.edu.gh
leveh.sandra19@central.edu.gh
nana.akroway20@central.edu.gh
bridget.ampomah20@central.edu.gh
assafuah.caroline.naa20@central.edu.gh
botwey.janet20@central.edu.gh
precious.glover20@central.edu.gh
mensah.racheal.mawumenyo20@central.edu.gh
sakyiama.keziah.boateng20@central.edu.gh
adams.sandra19@central.edu.gh
agbessi.princess19@central.edu.gh
ahadzi.veronica19@central.edu.gh
asaah.christiana19@central.edu.gh
ellen.atuahene.opoku16@central.edu.gh
akua.bio@central.edu.gh
djossah.michelle19@central.edu.gh
galevo.yaamah19@central.edu.gh
morrison.queensta19@central.edu.gh
owusu.rita19@central.edu.gh
quayson.araba19@central.edu.gh
teye.theophila19@central.edu.gh
abdul.hikmata19@central.edu.gh
addo.rebeccah17@central.edu.gh
awurabena.amoh.twum17@central.edu.gh
michelle.annan17@central.edu.gh
asante.michelle18@central.edu.gh
banitsi.rachel18@central.edu.gh
botchway.leonie18@central.edu.gh
dekadjevi.marie19@central.edu.gh
frimpong.tracy18@central.edu.gh
kankam.osaah18@central.edu.gh
mensah.philippa18@central.edu.gh
ewoenam.nkansa17@central.edu.gh
ofei.getrude18@central.edu.gh
rachel.otoo@central.edu.gh
quartey.delia18@central.edu.gh
sebbie.irene.amaki@central.edu.gh
yakubu.selma18@central.edu.gh
emmanuella.zewu17@central.edu.gh
agbemor.yvonne19@central.edu.gh
awuah.nancy18@central.edu.gh
kudolo.bless19@central.edu.gh
brefaaidoo@gmail.com
djenniferama@ymail.com
cofakos@gmail.com
eotutuboateng22@gmail.com
ruthgakpetor5@gmail.com
rachaelsevor71@gmail.com
christiana.baah19@central.edu.gh
amaara.diana20@central.edu.gh
arthur.sarah20@central.edu.gh
dablah.shirley.cecilia20@central.edu.gh
gbetanu.christabel.akorfa20@central.edu.gh
monney.viola.araba20@central.edu.gh
osman.marifuatu20@central.edu.gh
adams.sheila20@central.edu.gh
asiamah.angela20@central.edu.gh
matsakawo.ghislaine20@central.edu.gh
blankson.auntie18@central.edu.gh
frimpong.alberta19@central.edu.gh
korleki.akpey@central.edu.gh
anim.patience19@central.edu.gh
attafuah.nana19@central.edu.gh
bruce.zaneta19@central.edu.gh
darmoe.esime19@central.edu.gh
mensah.dorcas19@central.edu.gh
ofori.gloria19@central.edu.gh
jennifer.owusu.mensah@central.edu.gh
simpson.susanette19@central.edu.gh
andoh.rebecca20@central.edu.gh
ramatu.fuseini@central.edu.gh
doreen.nanor.yamoah17@central.edu.gh
wil.mary19@central.edu.gh
    # Add more email addresses here as needed
]
